Refactored StateHandler
4201VitruvianBots/ChargedUp2023 pull request #307
Opened 2023-04-01 20:03 UTC by SherazF

2023-04-01 21:33 UTC, Mason-Beard commented on src/main/java/frc/robot/Constants.java
> +      DANGER_ZONE(ZONE.ALPHA.ordinal()),
change to 0

2023-04-01 21:33 UTC, Mason-Beard commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +        case 0: // ALPHA
Add DangerZone

2023-04-01 23:08 UTC, AndrewKempen requested changes

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/commands/statehandler/SetSetpoint.java
> +    m_StateHandler.setDesiredSetpoint(SETPOINT.STOWED);
Is setting to stowed really what we want here? I think this command should be a simple set setpoint command, and if we want one that goes to stowed always after we should add another command that is like SetSetpointThenStow

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
>  import frc.robot.Constants.STATEHANDLER.*;
Do we still want this import *?

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
>    public SUPERSTRUCTURE_STATE getCurrentZone() {
This sounds like it should be getCurrentState not zone

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +    } else m_nextZone = ZONE_TRANSITIONS.GAMMA_TO_ALPHA;
So it looks like we default to transitioning from gamma to alpha when we are going to the same state that we are in? This doesn't seem right. (If it is, add a comment explaining)

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +          m_currentZone= SUPERSTRUCTURE_STATE.BETA_ZONE;
```suggestion
          m_currentZone = SUPERSTRUCTURE_STATE.BETA_ZONE;
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +          m_currentZone=SUPERSTRUCTURE_STATE.ALPHA_ZONE;
```suggestion
          m_currentZone = SUPERSTRUCTURE_STATE.ALPHA_ZONE;
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +          m_currentZone= SUPERSTRUCTURE_STATE.GAMMA_ZONE;
```suggestion
          m_currentZone = SUPERSTRUCTURE_STATE.GAMMA_ZONE;
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
>            //          m_wrist.setUpperLimit(WRIST.THRESHOLD.HIGH_MAX.get());
```suggestion
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +          m_currentZone= SUPERSTRUCTURE_STATE.BETA_ZONE;
```suggestion
          m_currentZone = SUPERSTRUCTURE_STATE.BETA_ZONE;
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +        m_currentZone= SUPERSTRUCTURE_STATE.ALPHA_ZONE;
```suggestion
        m_currentZone = SUPERSTRUCTURE_STATE.ALPHA_ZONE;
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +      if (m_elevator.getHeightMeters() < ELEVATOR.THRESHOLD.BETA_MAX.get()) {
We're transitioning to alpha but check beta max? this seems wrong

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
>            //            if (m_wrist.getPositionRadians() < WRIST.THRESHOLD.HIGH_MAX.get()) {
```suggestion
```

2023-04-01 23:08 UTC, AndrewKempen commented on src/main/java/frc/robot/subsystems/StateHandler.java
> +  public void setElevatorLowerLimitMeters(double lowerLimitMeters) {
Can we pull these functions out of elevator subsystem with these changes?

2023-04-01 23:36 UTC, SherazF commented on src/main/java/frc/robot/Constants.java
> +      ALPHA_MIN(ABSOLUTE_MIN.get()),
Comment made

2023-04-01 23:37 UTC, SherazF commented on src/main/java/frc/robot/Constants.java
> +      ALPHA_MAX(Units.inchesToMeters(4)),
Comment made

2023-04-01 23:42 UTC, SherazF commented on src/main/java/frc/robot/Constants.java
> +      STOWED(ZONE.ALPHA.ordinal()),
done

2023-04-01 23:46 UTC, SherazF commented on src/main/java/frc/robot/Constants.java
> +      GAMMA_TO_ALPHA;
Alpha to Gamma uses the correct logic to transition (alpha --> beta --> gamma), but when going from gamma to alpha, it would get stuck at the bottom of gamma, so we added to gamma to alpha state. With these transitions, we're able to make all the movements that we currently need (score high, score mid to intaking/stowed) with problems

2023-04-01 23:46 UTC, SherazF commented on src/main/java/frc/robot/RobotContainer.java
> +  // private final DistanceSensor m_distanceSensor = new DistanceSensor();
Removed

2023-04-01 23:47 UTC, SherazF commented on src/main/java/frc/robot/RobotContainer.java
> +        .onTrue(new SetSetpoint(m_stateHandler, m_elevator, m_wrist, SETPOINT.INTAKING_EXTENDED));
Should be whileTrue, has been updated

2023-04-01 23:48 UTC, SherazF commented on src/main/java/frc/robot/RobotContainer.java
> +    // m_distanceSensor.updateSmartDashboard();
Deleted

2023-04-04 01:47 UTC, jonathandao0 commented on src/main/java/frc/robot/commands/statehandler/SetSetpoint.java
> +    return false;
Adding an end condition breaks TeleOp functionality - Wrist/Elevator immediately goes to stowed once the command ends

2023-04-04 01:49 UTC, jonathandao0 approved these changes

2023-04-04 01:49 UTC, merged